# Generated by Django 5.2.1 on 2026-02-25 14:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurnameMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('surname', models.CharField(db_index=True, help_text='Nepali surname (e.g., के.सी., थापा, मगर)', max_length=100, unique=True)),
                ('caste_group', models.CharField(choices=[('brahmin', 'Brahmin (ब्राह्मण)'), ('chhetri', 'Chhetri (क्षेत्री)'), ('janajati', 'Janajati (जनजाति)'), ('dalit', 'Dalit (दलित)'), ('madhesi', 'Madhesi/Tharu (मधेसी/थारू)'), ('muslim', 'Muslim (मुस्लिम)'), ('other', 'Other (अन्य)'), ('unknown', 'Unknown (अज्ञात)')], db_index=True, help_text='Caste/ethnic group this surname belongs to', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is currently in use')),
                ('notes', models.TextField(blank=True, help_text='Notes about ambiguous cases or variations', null=True)),
            ],
            options={
                'verbose_name': 'Surname Mapping',
                'verbose_name_plural': 'Surname Mappings',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0, help_text='Total rows in CSV')),
                ('success_count', models.IntegerField(default=0, help_text='Successfully imported records')),
                ('error_count', models.IntegerField(default=0, help_text='Failed records')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True, help_text='Detailed error messages', null=True)),
                ('unmapped_surnames', models.TextField(blank=True, help_text='Surnames not found in mapping (JSON format)', null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Admin user who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload History',
                'verbose_name_plural': 'Upload Histories',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('voter_id', models.BigIntegerField(db_index=True, help_text='Unique voter ID from election commission', unique=True)),
                ('name', models.CharField(help_text='Full name in Nepali', max_length=200)),
                ('surname', models.CharField(db_index=True, help_text='Extracted surname (last word from name)', max_length=100)),
                ('age', models.IntegerField(db_index=True, help_text='Age in years', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(150)])),
                ('age_group', models.CharField(choices=[('gen_z', 'Gen Z / Young Voters (18-29)'), ('working', 'Working & Family (30-45)'), ('mature', 'Mature / Politically Active (46-60)'), ('senior', 'Senior Voters (60+)')], db_index=True, help_text='Categorized age group', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'पुरुष (Male)'), ('female', 'महिला (Female)'), ('other', 'अन्य (Other)')], db_index=True, help_text='Gender', max_length=20)),
                ('caste_group', models.CharField(blank=True, db_index=True, help_text='Caste group derived from surname', max_length=50, null=True)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('constituency', models.CharField(blank=True, db_index=True, help_text='Constituency/Area name (derived from filename)', max_length=100, null=True)),
                ('municipality', models.CharField(max_length=100)),
                ('ward', models.IntegerField(db_index=True)),
                ('center', models.CharField(max_length=200)),
                ('spouse', models.CharField(blank=True, help_text='Spouse name', max_length=200, null=True)),
                ('parent', models.CharField(blank=True, help_text='Parent names', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['age_group', 'gender'], name='detail_vote_age_gro_9cb476_idx'), models.Index(fields=['age_group', 'caste_group'], name='detail_vote_age_gro_dc0f92_idx'), models.Index(fields=['gender', 'caste_group'], name='detail_vote_gender_b751fb_idx'), models.Index(fields=['ward', 'age_group'], name='detail_vote_ward_61d0a3_idx')],
            },
        ),
    ]
