# Generated by Django 5.2.1 on 2026-02-26 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
