# Generated by Django 5.2.1 on 2026-02-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_uploadhistory_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='province',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
