#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# python /app/manage.py makemigrations
python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

python manage.py load_surname_mappings || true

#python manage.py import_voter_data bagmat
python /app/manage.py customcreatesuperuser
exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn_worker.UvicornWorker
